### ISSUE TITLE
[META] Next Steps for Web3Torrent

### ISSUE THREAD

**Issue by spersico** [statechannels/monorepo#1138]
- [ ] Get xstate-wallet to work instead of FakeChanneProvider. #1135 
- [ ] Figure out how we will set tab budget; what does App and Wallet need to do. #1132 
- [ ] Add local storage persistence to estate-wallet. 
- [ ] Add integration tests.
- [ ] Add “offline mode” capability and detection (coffee shop) #1129

**Comment by geoknee** [comment]
We'll use the project board to track next steps.
