### ISSUE TITLE
[embedded-wallet] Unit-Test everything!

### ISSUE THREAD

**Issue by joelalejandro** [statechannels/monorepo#199]
- [x] Generic UI components (#199)
- [x] JSON RPC router (#204)
- [x] Flow router (#205)
- [x] Message dispatchers (#206)
- [x] Onboarding flow (#208)
- [x] Budget Allocation dialog (#209)
- [x] No Hub dialog (#210)
- [x] Connect to Hub dialog (#211)
