### ISSUE TITLE
Stop torrenting and withdraw checklist

### ISSUE THREAD

**Issue by kerzhner** [statechannels/monorepo#2221]
- [x] I should be able to hit "Stop Torrenting" and live wires result in closed channels quickly (both if the torrent is DOWNLOADING and if the torrent is DONE)
- [x]  Withdrawal:  I should be able to hit withdraw after I hit "Stop Torrenting" 
- [x] When torrent object is destroyed, channels should still display (this might be working OK at the moment, since we get the infoHash from the URL, not the torrents array) 
- [x] If I refresh the page, I won’t be torrenting anymore. I should be able to withdraw. I should not see the “stop torrenting” button
