### ISSUE TITLE
[embedded-wallet] [channel-provider] Create new package for injecting `embedded-wallet`

### ISSUE THREAD

**Issue by joelalejandro** [statechannels/monorepo#277]
Derived from #258, I think we should move the [wallet.js](/statechannels/monorepo/tree/master/packages/embedded-wallet/public/wallet.js) loader to a package of its own, called `channel-provider`.

The benefits of this are non-trivial:

- Better dependency management
- Makes this piece of code testable
- Since it's not React code, it shouldn't be inside a React package

The build output from this package would be the aforementioned `wallet.js` file.

`embedded-wallet` will have a dependency on this package, and then copy `wallet.js` into `public/` after every `react-scripts build` execution.

So, these are the requirements:

- [x] Create the `channel-provider` package with TypeScript and a bundler (done in #278).
- [x] Refactor the `wallet.js` code into TypeScript, as it was started on #272 (done in #282).
- [x] Add unit tests for the code (done in #282).
- [x] Add bundling configuration (this is needed because EIP 1193 requires the use of `EventEmitter`; done in #278).
- [x] Install `@statechannels/channel-provider` as a dependency in `embedded-wallet` (done in #285).
- [x] Modify the build process so the output of `channel-provider` is exposed via the `embedded-wallet` `public` directory  (done in #285).
